version: '2'
services:

    web:
        build: ./
        volumes:
            - ./:/var/www/html/
        links:
            - db
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "b02023acdb0f09bc82499348ee081afb2885ca8e"


        # For Apache based image:
        #ports:
        #    - "8080:80"

        # For FPM/HHVM based image:
        expose:
            - "9000"

        # Autostart at boottime
        #restart: always

        # Send log output to syslog
        #logging:
        #    driver: "syslog"
        #    options:
        #        tag: "docker-web"

    # For FPM/HHVM based image:
    #nginx:
    #    build: ./nginx
    #    restart: always
    #    ports:
    #        - "8080:80"
    #    links:
    #        - web
    #    volumes_from:
    #        - web

    db:
        image: postgres:5.6
        environment:
            POSTGRES_USER: e2e4
            POSTGRES_PASSWORD: 123

        # Autostart at boottime
        #restart: always

